#!/bin/bash

if [ -z "$1" ]; then
    echo "Specify a job"
    exit 1
else
    JOB=$1
fi


# Sudo is required because docker can give arbitrary write permissions outside containers
# sudo gitlab-runner exec docker cinnabar --docker-volumes "$(pwd)/cache:/cache"
sudo gitlab-runner exec docker "$JOB" --docker-volumes "$(pwd)/cache:/cache"
